[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "composer"]

[start]
cmd = "php -S 0.0.0.0:${PORT} -t . index.php"


